name: DEPLOUY STAGING
on:
    pull_request:
        types: [closed]
        branches:
            - main
jobs:
  Deploy_Staging:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy no ambiente
        run: echo "Executando o deploy no ambiente de Main"